### ISSUE TITLE
Pages Issue

### ISSUE THREAD

**Issue by DrPamcodes** [DrPamcodes/cv_website#2]
Link the pages with the appropriate content.

**Comment by abitsalihu** [comment]
Hey @DrPamcodes, I would like to help with this issue, can you elaborate more on the issue? :)

**Comment by DrPamcodes** [comment]
Hi @abitsalihu, I wanted to link the navbar header with their respective sections because I didn't want to create new pages.  for example, Link skills on the header to the skills section. I just sorted it out, hopefully, you can check it out, any suggestions would be welcome. Thank you for offering to help, I really appreciate it.

**Comment by abitsalihu** [comment]
Hey, I'll check it out in a bit.

**Comment by abitsalihu** [comment]
@DrPamcodes I just checked the code it looks good, I can implement a smooth scroll if you want me to.

What it will basically do is that whenever someone clicks on the link it will smoothly scroll down and you see it scroll, not just pop down as it is doing right now. :)
