### ISSUE TITLE
[enhancement] The contact info icons are barely visible when hovered!

### ISSUE THREAD

**Issue by abitsalihu** [DrPamcodes/cv_website#4]
I noticed than when you hover over the "contact info" icons they're color makes them almost not visible:

Below is a video of the problem:

https://user-images.githubusercontent.com/94648837/191625843-1d4866a4-3a85-45f0-bbea-4917f1af3cfc.mov

**Comment by DrPamcodes** [comment]
I changed the hover colour to gold, to make it more visible. Thank you for flagging.
